### ISSUE TITLE
I didn't define POST, but it took a post request.

### ISSUE THREAD

**Issue by ritul-mtalkz** [jeka-kiselyov/fastify-mongoose-api#11]
I didn't define POST, but it took a post request when I got it. 

```
fastify.register(fastifyFormbody);
fastify.register(fastifyMongooseAPI, {
    models: mongoose.models,
    prefix: '/api/items',
    setDefaults: true,
    methods: ['get', 'patch', 'put', 'delete', 'options']
}
```

**Comment by EmilianoBruni** [comment]
I noticed the same problem. Looking at the code, it doesn't work because the methods option isn't use in the code. So whatever methods are specified, all routes are generated. 

I will patch this in my fork and submit a pull request.

**Comment by jeka-kiselyov** [comment]
Please do, @EmilianoBruni  Appreciate it. Thanks.

**Comment by EmilianoBruni** [comment]
I'm currently add support for validation and serialization using Ajv to works also under swagger. You can see a preview in my fork in [my validateSchema](https://github.com/EmilianoBruni/fastify-mongoose-api/tree/validationSchema) branch. This time I'll try to write tests too. 

As made this (a few days I suppose), I think it will be simple to fix methods filter.

**Comment by EmilianoBruni** [comment]
A few day are become a few hours. Fix in my branch.

**Comment by jeka-kiselyov** [comment]
Thanks. Closing this

**Comment by jeka-kiselyov** [comment]
Thank you. Closing this
