### ISSUE TITLE
this.remove() is not a function

### ISSUE THREAD

**Issue by misterioss** [jeka-kiselyov/fastify-mongoose-api#15]
Everything else works OK except for DELETE method.

I am not sure, maybe it's related to some deprecation.

I use:    
`fastify-mongoose-api": ^1.2.20`
`mongoose": "^7.6.3`

**Comment by jeka-kiselyov** [comment]
Will check today. Thanks for the report.

**Comment by jeka-kiselyov** [comment]
@misterioss fixed and published as 1.2.22  , now it should work with mongoose v7..

@EmilianoBruni published your fix as part of it too. But had little mess with merges. Seems everything is fine and tests are ok, but please take a quick look when you have time.

**Comment by EmilianoBruni** [comment]
@jeka-kiselyov Ok, will check in the weekend

**Comment by EmilianoBruni** [comment]
Everything seems to be working for me. I also replaced the references in all my projects to use the official version and I don't notice any problems.

**Comment by jeka-kiselyov** [comment]
Thank you @EmilianoBruni !
