### ISSUE TITLE
Fastify-swagger integration

### ISSUE THREAD

**Issue by mbaev** [jeka-kiselyov/fastify-mongoose-api#3]
Hello! This is awesome package!
I did deep research until finally I found this package!
I love it!

So dear Jeka, can you help to understand how to integrate the plugin with [fastify-swagger](https://github.com/fastify/fastify-swagger)?

it doesn't see the list of routes defined by the package.

**Comment by jeka-kiselyov** [comment]
Glad you find it helpful, @mbaev 

Tried it out of the box with default configuration on sample application and it works. Be sure you register fastify-swagger first and fastify-mongoose-api after it, as swager one adds hooks for new routes.

Parameters and sample responses are expectedly empty though. If while working on your project you have any ideas or pull requests which would generate this data for swagger - please let me know. 

![94c0ade3-dd20-47d2-92d5-2d5c92eea7b5](https://user-images.githubusercontent.com/1434612/103021790-6b50ed80-4553-11eb-8e20-e280a7e8c403.png)

**Comment by mbaev** [comment]
Oh, right! It works perfect!

It could be a good idea for the future to add an example response based on mongoose schema

```es6
// models/Center.js
import { Schema, model } from 'mongoose'

const schema = new Schema({
  name: {
    type: String,
    required: true
  },
  createdAt: {
    type: Date,
    required: true,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    required: true,
    default: Date.now
  }
})

export default model('Center', schema)
```

![image](https://user-images.githubusercontent.com/6450526/103097519-f8ae4380-4620-11eb-8bdb-4e8a8c26ca8b.png)

Thank you!
