### ISSUE TITLE
415 Unsupported Media Type

### ISSUE THREAD

**Issue by egoson** [jeka-kiselyov/fastify-mongoose-api#8]
`'use strict'
const { port, dbConfig } = require("./configuration");
// Require the framework and instantiate it
const fastifyMongooseAPI = require('fastify-mongoose-api');
const fastifyFormbody = require('fastify-formbody');
const mongoose = require('mongoose');
const fastify = require('fastify')();

const init = async () => {
  const mongooseConnection = await mongoose.connect('mongodb://auth_db:27017/auth', { useNewUrlParser: true, useUnifiedTopology: true });

  const authorSchema = mongoose.Schema({
    firstName: String,
    lastName: String,
    biography: String,
    created: { type: Date, default: Date.now }
  });

  const Author = mongooseConnection.model('Author', authorSchema);

  const bookSchema = mongoose.Schema({
    title: String,
    isbn: String,
    author: {  type: mongoose.Schema.Types.ObjectId,  ref: 'Author' },
    created: {  type: Date, default: Date.now }
  });

  const Book = mongooseConnection.model('Book', bookSchema);

  await fastify.register(fastifyFormbody);

  await fastify.register(fastifyMongooseAPI, {
    models: mongooseConnection.models,
    prefix: '/',
    setDefaults: true,
    methods: ['list', 'get', 'post', 'patch', 'put', 'delete', 'options']
  });

  await fastify.ready();
  await fastify.listen(port, '0.0.0.0');
}

init()
`

Frontend 

`async function saveAuthor () {
      const formData = new FormData();
      formData.append('title', text.value);
      await axios.post('http://localhost/auth/books', formData, {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        }})
    }`
    
Status Code: 415 Unsupported Media Type

I have been struggling with this for several days now, I need your help. I can't figure out what the problem is

UPD

I was able to send a valid request only with new URLSearchParams (), with FormData the request could not be sent

`async function saveAuthor () {
      const formData = new URLSearchParams();
      formData.append('title', text.value);
      await axios.post('http://localhost/auth/books', formData, {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        }
     })
    }`

**Comment by jeka-kiselyov** [comment]
@egoson I believe passing FormData to axios makes it send multipart http request (good for sending files), which is little different to handle and requires additional fastify plugin to install.

Is there any special need for this?

Just a 

```
await axios.post('http://localhost/auth/books', {title: text.value}, { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }) 
```

would work.

**Comment by jeka-kiselyov** [comment]
You can take a look at sample app frontend API class. It's very simple and it works: https://github.com/jeka-kiselyov/sample-fastify-mongoose-api-app/blob/master/frontend/src/includes/api.js

**Comment by egoson** [comment]
https://github.com/jeka-kiselyov/fastify-mongoose-api#sample-application-generated-api-routes


Here in the description of requests it is written to use FormData, so I tried to follow the documentation in every possible way

**Comment by egoson** [comment]
https://github.com/jeka-kiselyov/fastify-mongoose-api#sample-application-generated-api-routes

Here in the description of requests it is written to use FormData, so I tried to follow the documentation in every possible way

**Comment by jeka-kiselyov** [comment]
My bad, sorry for misleading you. I will update readme. @egoson

**Comment by jeka-kiselyov** [comment]
Docs updated.

**Comment by egoson** [comment]
I still cannot make a request like this. The data is not saved.

`await axios.post(
        "http://localhost/auth/books",
        { title: text.value },
        {
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
          },
        }
      );`
      
only works with `new URLSearchParams()`

**Comment by jeka-kiselyov** [comment]
@egoson does it work without `headers` parameter? Or content-type set to `application/json` ?
